mybatis:
  mapper-locations: classpath*:com/yk/blog/data/mapper/*.xml
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Wyy19970704
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
redis:
  url: 127.0.0.1
  port: 6379

email:
  from: 327958113@qq.com
  password: mrgmigvfixpdcajf
  host: smtp.qq.com

logging:
  level:
    com.yk.blog.data: debug
